POST http://localhost:8000/entity/create
accept: application/json
Content-Type: application/json

{
  "change_id": 0,
  "definition": {
    "apiVersion": "kubernetes.crossplane.io/v1alpha2",
    "kind": "Object",
    "metadata": {
      "name": "entity-test"
    },
    "spec": {
      "forProvider": {
        "manifest": {
          "apiVersion": "v1",
          "kind": "Namespace",
          "metadata": {
            "name": "entity-test"
          }
        }
      },
      "providerConfigRef": {
        "name": "provider-config-kubernetes"
      }
    }
  }
}

###

PUT http://localhost:8000/entity/update
accept: application/json
Content-Type: application/json

{
  "change_id": 0,
  "query": "select * from entity where id > 1",
  "lambdas": {
    ".spec.forProvider.manifest.metadata.name": "\"entity-test-full\""
  }
}

###

DELETE http://localhost:8000/entity/delete
accept: application/json
Content-Type: application/json

{
  "change_id": 0,
  "query": "select * from entity where id > 1"
}

###

GET http://localhost:8000/entity/read
accept: application/json
Content-Type: application/json

{
  "query": "select * from entity where definition->'$.metadata.name' = 'entity-test'"
}
