apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state-persister-pvc
  namespace: state-layer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: state-persister-schema
  namespace: state-layer
data:
  schema.sql: |
    CREATE DATABASE mydb;
    USE mydb;
    CREATE TABLE user (
        id BIGINT PRIMARY KEY,
        name VARCHAR(255)
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: state-persister
  namespace: state-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: state-persister
  template:
    metadata:
      labels:
        app: state-persister
    spec:
      volumes:
        - name: state-persister-data
          persistentVolumeClaim:
            claimName: state-persister-pvc
        - name: state-persister-schema
          configMap:
            name: state-persister-schema
      initContainers:
        - name: dolt-init
          image: dolthub/dolt:latest
          command:
            - sh
            - -c
            - |
              dolt config --global --add user.name "system"
              dolt config --global --add user.email "system@moam.agh.edu.pl"
              if [ ! -d ".dolt" ]; then
                echo ">> Initializing Dolt"
                dolt init
                echo ">> Applying schema"
                dolt sql < /schema/schema.sql
                dolt add .
                dolt commit -m "Initial schema"
              else
                echo ">> Dolt already initialized. Skipping."
              fi
          volumeMounts:
            - name: state-persister-data
              mountPath: /var/dolt
            - name: state-persister-schema
              mountPath: /schema
          workingDir: /var/dolt
      containers:
        - name: dolt
          image: dolthub/dolt:latest
          command: ["dolt", "sql-server"]
          ports:
            - containerPort: 3306
          env:
            - name: DOLT_SQL_SERVER_USER
              value: "root"
            - name: DOLT_SQL_SERVER_PASSWORD
              value: ""
          volumeMounts:
            - name: state-persister-data
              mountPath: /var/dolt
          workingDir: /var/dolt
