apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state-persister-pvc
  namespace: state-layer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: state-persister
  namespace: state-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: state-persister
  template:
    metadata:
      labels:
        app: state-persister
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: state-persister-storage
      volumes:
        - name: state-persister-storage
          persistentVolumeClaim:
            claimName: state-persister-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: state-persister
  namespace: state-layer
spec:
  selector:
    app: state-persister
  ports:
    - port: 5432
      targetPort: 5432
