apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state-persister-pvc
  namespace: state-layer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: state-persister-schema
  namespace: state-layer
data:
  schema.sql: |
    CREATE DATABASE state_persister_db;
    USE state_persister_db;
    
    CREATE TABLE rule (
        id BIGINT PRIMARY KEY,
        _condition VARCHAR(8192),
        _action TEXT
    );
    ALTER TABLE rule
    ADD CONSTRAINT unique_condition UNIQUE (_condition);
    
    CREATE TABLE metric (
        id BIGINT PRIMARY KEY,
        name VARCHAR(1024),
        query VARCHAR(8192)
    );
    ALTER TABLE metric
    ADD CONSTRAINT unique_metric_name UNIQUE (name);
    
    CREATE TABLE environment_entity (
        id BIGINT PRIMARY KEY,
        name VARCHAR(1024),
        namespace VARCHAR(1024),
        definition JSON
    );
    ALTER TABLE environment_entity
    ADD CONSTRAINT unique_name_namespace UNIQUE (name, namespace);
    
    CREATE TABLE environment_entity_label (
        id BIGINT PRIMARY KEY,
        environment_entity_id BIGINT,
        name VARCHAR(255),
        value VARCHAR(255),
        FOREIGN KEY (environment_entity_id) REFERENCES environment_entity(id)
    );
    ALTER TABLE environment_entity_label
    ADD CONSTRAINT unique_entity_label_name UNIQUE (environment_entity_id, name);
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: state-persister
  namespace: state-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: state-persister
  template:
    metadata:
      labels:
        app: state-persister
    spec:
      volumes:
        - name: state-persister-data
          persistentVolumeClaim:
            claimName: state-persister-pvc
        - name: state-persister-schema
          configMap:
            name: state-persister-schema
      initContainers:
        - name: dolt-init
          image: dolthub/dolt:latest
          command:
            - sh
            - -c
            - |
              echo ">> Configuring user"
              dolt config --global --add user.name "system"
              dolt config --global --add user.email "system@moam.agh.edu.pl"
              if [ ! -d ".dolt" ]; then
                echo ">> Initializing Dolt"
                dolt init
              else
                echo ">> Dolt already initialized. Skipping."
              fi
              if [ ! -d "state_persister_db" ]; then
                echo ">> Applying schema"
                dolt sql < /schema/schema.sql
                cd state_persister_db
                echo ">> Adding changes"
                dolt add .
                echo ">> Commiting"
                dolt commit -m "Initial schema"
                cd ..
              else
                echo ">> Schema already applied. Skipping."
              fi
              # https://www.dolthub.com/blog/2025-02-05-sql-server-removes-user-pass-args/
              echo ">> Creating the default user"
              dolt sql -q "CREATE USER IF NOT EXISTS '$DOLT_USERNAME' IDENTIFIED BY '$DOLT_PASSWORD'; GRANT ALL PRIVILEGES ON *.* TO '$DOLT_USERNAME' WITH GRANT OPTION;"
          env:
            - name: DOLT_USERNAME
              value: "root"
            - name: DOLT_PASSWORD
              value: "hunter2"
          volumeMounts:
            - name: state-persister-data
              mountPath: /var/dolt
            - name: state-persister-schema
              mountPath: /schema
          workingDir: /var/dolt
      containers:
        - name: dolt
          image: dolthub/dolt:latest
          command: ["dolt", "sql-server", "--host", "0.0.0.0"]
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: state-persister-data
              mountPath: /var/dolt
          workingDir: /var/dolt
---
apiVersion: v1
kind: Service
metadata:
  name: state-persister-svc
  namespace: state-layer
spec:
  selector:
    app: state-persister
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
# mysql -h state-persister-svc.state-layer.svc.cluster.local -u root -p
